pivot:
  working-dir: D:/LetsPivot
  original-csv:
    dir-name: OriginalCsv
    file-name: CarefulQuery.csv
  error-log:
    dir-name: ErrorLog
    file-name: app-error-%s.log
  result-xlsx:
    dir-name: ResultXlsx
    file-name: CarefulQuery.xlsx
  row-names: 業務代碼,科目編碼,科目名稱
  sum-column-names: 金額,原幣值
  credit-debit-name: 借貸方
